/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWfpRouteImport } from './routes/_app/wfp'
import { Route as AppTodosRouteImport } from './routes/_app/todos'
import { Route as AppHiringRouteImport } from './routes/_app/hiring'
import { Route as AppFyPlanningRouteImport } from './routes/_app/fy-planning'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCarbonitesRouteImport } from './routes/_app/carbonites'
import { Route as AppCapacityRouteImport } from './routes/_app/capacity'
import { Route as AppAdminRouteImport } from './routes/_app/admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWfpRoute = AppWfpRouteImport.update({
  id: '/wfp',
  path: '/wfp',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/wfp.lazy').then((d) => d.Route))
const AppTodosRoute = AppTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/todos.lazy').then((d) => d.Route))
const AppHiringRoute = AppHiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/hiring.lazy').then((d) => d.Route))
const AppFyPlanningRoute = AppFyPlanningRouteImport.update({
  id: '/fy-planning',
  path: '/fy-planning',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/fy-planning.lazy').then((d) => d.Route),
)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/dashboard.lazy').then((d) => d.Route),
)
const AppCarbonitesRoute = AppCarbonitesRouteImport.update({
  id: '/carbonites',
  path: '/carbonites',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/carbonites.lazy').then((d) => d.Route),
)
const AppCapacityRoute = AppCapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/capacity.lazy').then((d) => d.Route))
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/admin.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/capacity': typeof AppCapacityRoute
  '/carbonites': typeof AppCarbonitesRoute
  '/dashboard': typeof AppDashboardRoute
  '/fy-planning': typeof AppFyPlanningRoute
  '/hiring': typeof AppHiringRoute
  '/todos': typeof AppTodosRoute
  '/wfp': typeof AppWfpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/capacity': typeof AppCapacityRoute
  '/carbonites': typeof AppCarbonitesRoute
  '/dashboard': typeof AppDashboardRoute
  '/fy-planning': typeof AppFyPlanningRoute
  '/hiring': typeof AppHiringRoute
  '/todos': typeof AppTodosRoute
  '/wfp': typeof AppWfpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/capacity': typeof AppCapacityRoute
  '/_app/carbonites': typeof AppCarbonitesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fy-planning': typeof AppFyPlanningRoute
  '/_app/hiring': typeof AppHiringRoute
  '/_app/todos': typeof AppTodosRoute
  '/_app/wfp': typeof AppWfpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/capacity'
    | '/carbonites'
    | '/dashboard'
    | '/fy-planning'
    | '/hiring'
    | '/todos'
    | '/wfp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/capacity'
    | '/carbonites'
    | '/dashboard'
    | '/fy-planning'
    | '/hiring'
    | '/todos'
    | '/wfp'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/capacity'
    | '/_app/carbonites'
    | '/_app/dashboard'
    | '/_app/fy-planning'
    | '/_app/hiring'
    | '/_app/todos'
    | '/_app/wfp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wfp': {
      id: '/_app/wfp'
      path: '/wfp'
      fullPath: '/wfp'
      preLoaderRoute: typeof AppWfpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/todos': {
      id: '/_app/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AppTodosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hiring': {
      id: '/_app/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof AppHiringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fy-planning': {
      id: '/_app/fy-planning'
      path: '/fy-planning'
      fullPath: '/fy-planning'
      preLoaderRoute: typeof AppFyPlanningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carbonites': {
      id: '/_app/carbonites'
      path: '/carbonites'
      fullPath: '/carbonites'
      preLoaderRoute: typeof AppCarbonitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/capacity': {
      id: '/_app/capacity'
      path: '/capacity'
      fullPath: '/capacity'
      preLoaderRoute: typeof AppCapacityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCapacityRoute: typeof AppCapacityRoute
  AppCarbonitesRoute: typeof AppCarbonitesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFyPlanningRoute: typeof AppFyPlanningRoute
  AppHiringRoute: typeof AppHiringRoute
  AppTodosRoute: typeof AppTodosRoute
  AppWfpRoute: typeof AppWfpRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCapacityRoute: AppCapacityRoute,
  AppCarbonitesRoute: AppCarbonitesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFyPlanningRoute: AppFyPlanningRoute,
  AppHiringRoute: AppHiringRoute,
  AppTodosRoute: AppTodosRoute,
  AppWfpRoute: AppWfpRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
