/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTodosRouteImport } from './routes/_app/todos'
import { Route as AppScenariosRouteImport } from './routes/_app/scenarios'
import { Route as AppHiringRouteImport } from './routes/_app/hiring'
import { Route as AppFyPlanningRouteImport } from './routes/_app/fy-planning'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppCarbonitesRouteImport } from './routes/_app/carbonites'
import { Route as AppCapacityPlanRouteImport } from './routes/_app/capacity-plan'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppScenariosIdRouteImport } from './routes/_app/scenarios.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTodosRoute = AppTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/todos.lazy').then((d) => d.Route))
const AppScenariosRoute = AppScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/scenarios.lazy').then((d) => d.Route),
)
const AppHiringRoute = AppHiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/hiring.lazy').then((d) => d.Route))
const AppFyPlanningRoute = AppFyPlanningRouteImport.update({
  id: '/fy-planning',
  path: '/fy-planning',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/fy-planning.lazy').then((d) => d.Route),
)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/chat.lazy').then((d) => d.Route))
const AppCarbonitesRoute = AppCarbonitesRouteImport.update({
  id: '/carbonites',
  path: '/carbonites',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/carbonites.lazy').then((d) => d.Route),
)
const AppCapacityPlanRoute = AppCapacityPlanRouteImport.update({
  id: '/capacity-plan',
  path: '/capacity-plan',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/capacity-plan.lazy').then((d) => d.Route),
)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/admin.lazy').then((d) => d.Route))
const AppScenariosIdRoute = AppScenariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppScenariosRoute,
} as any).lazy(() =>
  import('./routes/_app/scenarios.$id.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/capacity-plan': typeof AppCapacityPlanRoute
  '/carbonites': typeof AppCarbonitesRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/fy-planning': typeof AppFyPlanningRoute
  '/hiring': typeof AppHiringRoute
  '/scenarios': typeof AppScenariosRouteWithChildren
  '/todos': typeof AppTodosRoute
  '/scenarios/$id': typeof AppScenariosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/capacity-plan': typeof AppCapacityPlanRoute
  '/carbonites': typeof AppCarbonitesRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/fy-planning': typeof AppFyPlanningRoute
  '/hiring': typeof AppHiringRoute
  '/scenarios': typeof AppScenariosRouteWithChildren
  '/todos': typeof AppTodosRoute
  '/scenarios/$id': typeof AppScenariosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/capacity-plan': typeof AppCapacityPlanRoute
  '/_app/carbonites': typeof AppCarbonitesRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fy-planning': typeof AppFyPlanningRoute
  '/_app/hiring': typeof AppHiringRoute
  '/_app/scenarios': typeof AppScenariosRouteWithChildren
  '/_app/todos': typeof AppTodosRoute
  '/_app/scenarios/$id': typeof AppScenariosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/capacity-plan'
    | '/carbonites'
    | '/chat'
    | '/dashboard'
    | '/fy-planning'
    | '/hiring'
    | '/scenarios'
    | '/todos'
    | '/scenarios/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/capacity-plan'
    | '/carbonites'
    | '/chat'
    | '/dashboard'
    | '/fy-planning'
    | '/hiring'
    | '/scenarios'
    | '/todos'
    | '/scenarios/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/capacity-plan'
    | '/_app/carbonites'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/fy-planning'
    | '/_app/hiring'
    | '/_app/scenarios'
    | '/_app/todos'
    | '/_app/scenarios/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/todos': {
      id: '/_app/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AppTodosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scenarios': {
      id: '/_app/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof AppScenariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hiring': {
      id: '/_app/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof AppHiringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fy-planning': {
      id: '/_app/fy-planning'
      path: '/fy-planning'
      fullPath: '/fy-planning'
      preLoaderRoute: typeof AppFyPlanningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carbonites': {
      id: '/_app/carbonites'
      path: '/carbonites'
      fullPath: '/carbonites'
      preLoaderRoute: typeof AppCarbonitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/capacity-plan': {
      id: '/_app/capacity-plan'
      path: '/capacity-plan'
      fullPath: '/capacity-plan'
      preLoaderRoute: typeof AppCapacityPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scenarios/$id': {
      id: '/_app/scenarios/$id'
      path: '/$id'
      fullPath: '/scenarios/$id'
      preLoaderRoute: typeof AppScenariosIdRouteImport
      parentRoute: typeof AppScenariosRoute
    }
  }
}

interface AppScenariosRouteChildren {
  AppScenariosIdRoute: typeof AppScenariosIdRoute
}

const AppScenariosRouteChildren: AppScenariosRouteChildren = {
  AppScenariosIdRoute: AppScenariosIdRoute,
}

const AppScenariosRouteWithChildren = AppScenariosRoute._addFileChildren(
  AppScenariosRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCapacityPlanRoute: typeof AppCapacityPlanRoute
  AppCarbonitesRoute: typeof AppCarbonitesRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFyPlanningRoute: typeof AppFyPlanningRoute
  AppHiringRoute: typeof AppHiringRoute
  AppScenariosRoute: typeof AppScenariosRouteWithChildren
  AppTodosRoute: typeof AppTodosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCapacityPlanRoute: AppCapacityPlanRoute,
  AppCarbonitesRoute: AppCarbonitesRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFyPlanningRoute: AppFyPlanningRoute,
  AppHiringRoute: AppHiringRoute,
  AppScenariosRoute: AppScenariosRouteWithChildren,
  AppTodosRoute: AppTodosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
